import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
const read=(path)=>readFile(new URL(`../${path}`,import.meta.url),"utf8");

test("Asaas secrets stay server-only",async()=>{const [admin,client,env]=await Promise.all([read("lib/supabase/admin.ts"),read("modules/payments/infrastructure/asaas-client.ts"),read(".env.example")]);assert.match(admin,/server-only/);assert.match(client,/ASAAS_API_KEY/);assert.doesNotMatch(env,/NEXT_PUBLIC_ASAAS|NEXT_PUBLIC_SUPABASE_SECRET/)});
test("missing admin configuration remains a typed payment error",async()=>{const [admin,route]=await Promise.all([read("lib/supabase/admin.ts"),read("app/api/payments/pix/route.ts")]);assert.match(admin,/new PaymentError\("PAYMENT_CONFIGURATION_MISSING"\)/);assert.match(route,/PAYMENT_CONFIGURATION_MISSING[^\n]*503/);assert.match(route,/checkout preparation failed/);assert.doesNotMatch(route,/console\.error\([^\n]*(cpf|secret|body)/)});
test("payment preparation exposes safe stage diagnostics",async()=>{const service=await read("modules/payments/application/payment-service.ts");assert.match(service,/preparation started/);assert.match(service,/checkout context loaded/);assert.match(service,/open attempt checked/);assert.match(service,/payment attempt ready/);assert.doesNotMatch(service,/console\.(info|error)\([^\n]*(userId|cpf|email|address)/)});
test("payments reject expired checkout drafts",async()=>{const repository=await read("modules/payments/infrastructure/supabase-payment-repository.ts");assert.match(repository,/\.gt\("expires_at", new Date\(\)\.toISOString\(\)\)/)});
test("card payments use a normalized delivery phone fallback",async()=>{const [repository,service,route,form]=await Promise.all([read("modules/payments/infrastructure/supabase-payment-repository.ts"),read("modules/payments/application/payment-service.ts"),read("app/api/payments/card/route.ts"),read("app/checkout/checkout-form.tsx")]);assert.match(repository,/select\("phone, postal_code, street, number, neighborhood"\)/);assert.match(repository,/profilePhone \|\| addressPhone \|\| null/);assert.match(service,/PHONE_REQUIRED/);assert.match(route,/PHONE_REQUIRED[^\n]*422/);assert.match(form,/Informe um telefone com DDD/)});
test("Asaas failures log only safe provider diagnostics",async()=>{const client=await read("modules/payments/infrastructure/asaas-client.ts");assert.match(client,/provider request failed/);assert.match(client,/status: response\.status/);assert.match(client,/errors: safeProviderErrors\(data\)/);assert.doesNotMatch(client,/console\.error\([^\n]*(apiKey|cpf|body)/)});
test("Pix uses external reference and retrieves QR code",async()=>{const client=await read("modules/payments/infrastructure/asaas-client.ts");assert.match(client,/externalReference: attemptId/);assert.match(client,/pixQrCode/);assert.doesNotMatch(client,/polling|setInterval/i)});
test("card data is never persisted",async()=>{const files=await Promise.all([read("modules/payments/infrastructure/supabase-payment-repository.ts"),read("app/api/payments/card/route.ts")]);assert.doesNotMatch(files[0],/creditCard|ccv|expiry|card\.number/);assert.doesNotMatch(files[1],/\.from\(|console\.log/)});
test("webhook validates token and is idempotent",async()=>{const route=await read("app/api/webhooks/asaas/route.ts");const repository=await read("modules/payments/infrastructure/supabase-payment-repository.ts");assert.match(route,/timingSafeEqual/);assert.match(route,/asaas-access-token/);assert.match(repository,/23505/)});
test("webhook reconciles provider status even for generic payment updates",async()=>{const route=await read("app/api/webhooks/asaas/route.ts");assert.match(route,/statusByProvider/);assert.match(route,/statusByEvent\[parsed\.data\.event\] \?\?/);assert.match(route,/CONFIRMED:"CONFIRMED"/);assert.match(route,/RECEIVED:"RECEIVED"/)});
test("synchronous Asaas confirmation records the confirmation timestamp",async()=>{const repository=await read("modules/payments/infrastructure/supabase-payment-repository.ts");assert.match(repository,/statusByProvider\[providerStatus\]/);assert.match(repository,/\["CONFIRMED","RECEIVED"\]\.includes\(status\)/);assert.match(repository,/confirmed_at:confirmedAt/)});
test("reused attempts are reconciled against Asaas without creating another charge",async()=>{const [service,contracts,client,repository]=await Promise.all([read("modules/payments/application/payment-service.ts"),read("modules/payments/application/payment-contracts.ts"),read("modules/payments/infrastructure/asaas-client.ts"),read("modules/payments/infrastructure/supabase-payment-repository.ts")]);assert.match(contracts,/getPayment\(paymentId: string\)/);assert.match(client,/\/payments\/\$\{encodeURIComponent\(paymentId\)\}/);assert.match(service,/this\.gateway\.getPayment\(attempt\.providerPaymentId\)/);assert.match(service,/return this\.reconcile\(open\)/);assert.match(repository,/"CONFIRMED","RECEIVED"/)});

test("webhook bypasses session login while keeping token authentication",async()=>{
  const proxy=await read("lib/supabase/proxy.ts");
  const route=await read("app/api/webhooks/asaas/route.ts");
  assert.match(proxy,/PUBLIC_EXACT_PATHS[^\n]*\/api\/webhooks\/asaas/);
  assert.match(proxy,/PUBLIC_EXACT_PATHS\.has\(request\.nextUrl\.pathname\)/);
  assert.match(route,/asaas-access-token/);
  assert.match(route,/status:401/);
});
