import Link from"next/link";import{redirect}from"next/navigation";import{createServerSupabaseClient}from"../../../lib/supabase/server";import{SupabaseWalletRepository}from"../../../modules/wallet/infrastructure/supabase-wallet-repository";import{requestPayoutAction}from"./actions";import{AffiliateNav}from"../affiliate-nav";import"../affiliate.css";
const money=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}),date=new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short",timeZone:"America/Bahia"});
const status:Record<string,string>={REQUESTED:"Em análise",PROCESSING:"Em processamento",PAID:"Pago",REJECTED:"Recusado",CANCELLED:"Cancelado"};
export default async function WalletPage(){const client=await createServerSupabaseClient(),{data:{user}}=await client.auth.getUser();if(!user)redirect("/login?next=/afiliados/carteira");const wallet=await new SupabaseWalletRepository(client).load(user.id),total=wallet.balance.pending+wallet.balance.available+wallet.balance.paid;return <main className="affiliate-app"><AffiliateNav active="wallet"/><section className="affiliate-workspace"><header className="affiliate-topbar"><div><small>Portal do afiliado</small><b>CARTEIRA E EXTRATO</b></div><div><span>Disponível <b>{money.format(wallet.balance.available)}</b></span><Link href="/afiliados/painel">Voltar ao painel</Link></div></header><div className="affiliate-content">
<section className="wallet-hero"><div><small>SEU FINANCEIRO</small><h1>Carteira BEYOU</h1><p>Da comissão gerada ao saque, cada movimentação permanece registrada.</p></div><div><small>TOTAL MOVIMENTADO</small><strong>{money.format(total)}</strong></div></section>
<section className="affiliate-metrics wallet-metrics"><article><small>A liberar</small><strong>{money.format(wallet.balance.pending)}</strong><p>Aguardando prazo de liberação</p></article><article><small>Disponível</small><strong>{money.format(wallet.balance.available)}</strong><p>Pronto para solicitar saque</p></article><article><small>Pago</small><strong>{money.format(wallet.balance.paid)}</strong><p>Saques já concluídos</p></article></section>
<section className="dashboard-grid"><article className="affiliate-card payout-card"><small>SAQUES</small><h2>Solicitar saque</h2><form action={requestPayoutAction}><label>Valor disponível<input name="amount" type="number" min="0.01" step="0.01" max={wallet.balance.available} placeholder="0,00" required/></label><label>Tipo da chave Pix<select name="pixKeyType"><option>CPF</option><option>CNPJ</option><option>EMAIL</option><option>PHONE</option><option>EVP</option></select></label><label>Chave Pix<input name="pixKey" autoComplete="off" required/></label><button disabled={wallet.balance.available<=0}>Solicitar saque</button></form><p className="wallet-note">Ao solicitar, o valor é reservado imediatamente e segue para análise financeira. A chave completa não aparece no extrato.</p></article><article className="affiliate-card"><small>ACOMPANHAMENTO</small><h2>Meus saques</h2><div className="commission-list payout-list">{wallet.payouts.map(x=><p key={x.id}><span><i className={`payout-status status-${x.status.toLowerCase()}`}>{status[x.status]??x.status}</i><small>{x.pixKeyMasked} · {date.format(new Date(x.requestedAt))}</small></span><b>{money.format(x.amount)}</b></p>)}{!wallet.payouts.length&&<p>Nenhum saque solicitado.</p>}</div></article></section>
<section className="affiliate-card wallet-statement"><div className="statement-title"><div><small>HISTÓRICO FINANCEIRO</small><h2>Extrato completo</h2></div><span>{wallet.entries.length} lançamentos</span></div><div className="commission-list">{wallet.entries.map(x=>{const value=x.pendingDelta||x.availableDelta||x.paidDelta;return <p key={x.id}><span><b>{x.type.replaceAll("_"," ")}</b><small>{date.format(new Date(x.createdAt))}</small></span><b className={value>=0?"positive":"negative"}>{value>0?"+ ":""}{money.format(value)}</b></p>})}{!wallet.entries.length&&<p>Nenhum lançamento registrado.</p>}</div></section>
</div></section></main>}
