"use client";
import { useMemo, useState } from "react";
import Image from "next/image";
import Link from "next/link";
import type { Product } from "../../modules/products/domain/product";
import { AddToCartButton } from "../../modules/checkout/presentation/cart-store";
const money=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
export function StoreCatalog({products}:{products:readonly Product[]}){
 const[q,setQ]=useState("");const[sort,setSort]=useState("featured");const[ceiling,setCeiling]=useState(999999);
 const visible=useMemo(()=>products.filter(p=>(p.name+" "+p.shortDescription).toLowerCase().includes(q.toLowerCase())&&(p.priceCents??999999)<=ceiling).sort((a,b)=>sort==="low"?(a.priceCents??Infinity)-(b.priceCents??Infinity):sort==="high"?(b.priceCents??0)-(a.priceCents??0):Number(b.featured)-Number(a.featured)),[products,q,sort,ceiling]);
 return <><div className="catalog-toolbar"><label><span>Buscar produtos</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar por nome, benefício ou objetivo…"/></label><label><span>Ordenar</span><select value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Destaques</option><option value="low">Menor preço</option><option value="high">Maior preço</option></select></label><div className="price-filters"><button className={ceiling===10000?"active":""} onClick={()=>setCeiling(10000)}>R$ 0–100</button><button className={ceiling===30000?"active":""} onClick={()=>setCeiling(30000)}>Até R$ 300</button><button className={ceiling===999999?"active":""} onClick={()=>setCeiling(999999)}>Todos</button></div></div><p className="catalog-count">{visible.length} {visible.length===1?"produto":"produtos"}</p><div className="catalog-grid">{visible.map(product=><article className="catalog-card" key={product.id}><Link className="catalog-card-link" href={`/loja/${product.slug}`} aria-label={`Ver ${product.name}`}><div className="catalog-pack"><Image src={product.imageUrl??"https://beyou-teste-nine.vercel.app/beyou-box-hero.webp"} alt={product.name} width={992} height={794}/></div>{product.featured&&<small className="featured-badge">DESTAQUE</small>}<h3>{product.name}</h3><p>{product.shortDescription}</p><strong>{product.priceCents===null?"Em breve":money.format(product.priceCents/100)}</strong></Link><div className="catalog-card-actions"><Link href={`/loja/${product.slug}`}>Ver detalhes</Link><AddToCartButton productId={product.id} disabled={product.stockQuantity<1||product.priceCents===null}>+ Carrinho</AddToCartButton></div></article>)}</div>{visible.length===0&&<p className="catalog-message">Nenhum produto corresponde aos filtros.</p>}</>
}
