create or replace function public.request_affiliate_payout(p_user_id uuid,p_amount numeric,p_pix_key_type text,p_pix_key text) returns uuid language plpgsql security definer set search_path='' as $$
declare v_available numeric;v_id uuid;v_masked text;
begin if p_user_id is null or not exists(select 1 from public.affiliate_profiles where user_id=p_user_id and active) then raise exception 'AFFILIATE_REQUIRED';end if;if p_amount is null or p_amount<=0 then raise exception 'INVALID_AMOUNT';end if;if p_pix_key_type not in('CPF','CNPJ','EMAIL','PHONE','EVP') or length(trim(p_pix_key))<3 then raise exception 'INVALID_PIX_KEY';end if;
 perform pg_advisory_xact_lock(hashtextextended(p_user_id::text,0));select coalesce(available_amount,0) into v_available from public.affiliate_wallet_balances where affiliate_user_id=p_user_id;
 if coalesce(v_available,0)<p_amount then raise exception 'INSUFFICIENT_BALANCE';end if;v_masked:=left(trim(p_pix_key),2)||repeat('*',greatest(length(trim(p_pix_key))-4,2))||right(trim(p_pix_key),2);
 insert into public.affiliate_payout_requests(affiliate_user_id,amount,pix_key_type,pix_key_masked,pix_key_encrypted) values(p_user_id,p_amount,p_pix_key_type,v_masked,encode(extensions.pgp_sym_encrypt(trim(p_pix_key),current_setting('app.settings.jwt_secret',true)),'base64')) returning id into v_id;
 insert into public.affiliate_wallet_entries(affiliate_user_id,payout_request_id,entry_type,available_delta,idempotency_key) values(p_user_id,v_id,'PAYOUT_REQUESTED',-p_amount,'payout:'||v_id||':requested');return v_id;end $$;
create or replace function public.list_affiliate_payouts_for_admin(p_actor_id uuid) returns table(id uuid,affiliate_user_id uuid,affiliate_name text,amount numeric,status text,pix_key_type text,pix_key text,pix_key_masked text,requested_at timestamptz,processed_at timestamptz,rejection_reason text) language plpgsql security definer set search_path='' as $$
begin if not exists(select 1 from public.profiles where profiles.id=p_actor_id and profiles.role='admin') then raise exception 'ADMIN_REQUIRED';end if;return query select r.id,r.affiliate_user_id,coalesce(p.full_name,'Afiliado BEYOU'),r.amount,r.status,r.pix_key_type,extensions.pgp_sym_decrypt(decode(r.pix_key_encrypted,'base64'),current_setting('app.settings.jwt_secret',true))::text,r.pix_key_masked,r.requested_at,r.processed_at,r.rejection_reason from public.affiliate_payout_requests r join public.profiles p on p.id=r.affiliate_user_id order by case when r.status='REQUESTED' then 0 else 1 end,r.requested_at desc limit 200;end $$;
revoke all on function public.request_affiliate_payout(uuid,numeric,text,text),public.list_affiliate_payouts_for_admin(uuid) from public,anon,authenticated;
grant execute on function public.request_affiliate_payout(uuid,numeric,text,text),public.list_affiliate_payouts_for_admin(uuid) to service_role;
