begin;
revoke update on table public.profiles from authenticated;
grant update (full_name, phone, cpf, avatar_url, birth_date, city, state, updated_at) on table public.profiles to authenticated;
drop policy if exists affiliate_profile_own_update on public.affiliate_profiles;
revoke insert, update, delete on table public.affiliate_profiles from authenticated;
drop policy if exists transactions_insert_own on public.becoin_transactions;
revoke insert, update, delete on table public.becoin_transactions from authenticated;
revoke insert, update, delete on table public.becoin_wallets from authenticated;
drop policy if exists subscriptions_own_all on public.subscriptions;
create policy subscriptions_select_own on public.subscriptions for select to authenticated using ((select auth.uid()) = user_id);
revoke insert, update, delete on table public.subscriptions from authenticated;
drop policy if exists notifications_own_all on public.notifications;
create policy notifications_select_own on public.notifications for select to authenticated using ((select auth.uid()) = user_id);
revoke insert, update, delete on table public.notifications from authenticated;
drop policy if exists orders_insert_own on public.orders;
drop policy if exists order_items_insert_own on public.order_items;
revoke insert, update, delete on table public.orders from authenticated;
revoke insert, update, delete on table public.order_items from authenticated;
revoke insert, update, delete on table public.commission_ledger from authenticated;
commit;
