drop function if exists public.request_affiliate_payout(numeric,text,text);
drop function if exists public.release_affiliate_commission(uuid);
drop function if exists public.process_affiliate_payout(uuid,text,text);

create or replace function public.request_affiliate_payout(p_user_id uuid,p_amount numeric,p_pix_key_type text,p_pix_key text) returns uuid language plpgsql security definer set search_path='' as $$
declare v_available numeric;v_id uuid;v_masked text;
begin if p_user_id is null or not exists(select 1 from public.affiliate_profiles where user_id=p_user_id and active) then raise exception 'AFFILIATE_REQUIRED';end if;if p_amount is null or p_amount<=0 then raise exception 'INVALID_AMOUNT';end if;if p_pix_key_type not in('CPF','CNPJ','EMAIL','PHONE','EVP') or length(trim(p_pix_key))<3 then raise exception 'INVALID_PIX_KEY';end if;
 perform pg_advisory_xact_lock(hashtextextended(p_user_id::text,0));select coalesce(available_amount,0) into v_available from public.affiliate_wallet_balances where affiliate_user_id=p_user_id;
 if coalesce(v_available,0)<p_amount then raise exception 'INSUFFICIENT_BALANCE';end if;v_masked:=left(trim(p_pix_key),2)||repeat('*',greatest(length(trim(p_pix_key))-4,2))||right(trim(p_pix_key),2);
 insert into public.affiliate_payout_requests(affiliate_user_id,amount,pix_key_type,pix_key_masked,pix_key_encrypted) values(p_user_id,p_amount,p_pix_key_type,v_masked,encode(pgp_sym_encrypt(trim(p_pix_key),current_setting('app.settings.jwt_secret',true)),'base64')) returning id into v_id;
 insert into public.affiliate_wallet_entries(affiliate_user_id,payout_request_id,entry_type,available_delta,idempotency_key) values(p_user_id,v_id,'PAYOUT_REQUESTED',-p_amount,'payout:'||v_id||':requested');return v_id;end $$;
create or replace function public.release_affiliate_commission(p_actor_id uuid,p_commission_id uuid) returns void language plpgsql security definer set search_path='' as $$
begin if not exists(select 1 from public.profiles where id=p_actor_id and role='admin') then raise exception 'ADMIN_REQUIRED';end if;update public.commission_ledger set status='released',released_at=now() where id=p_commission_id and status in('calculated','pending');if not found then raise exception 'COMMISSION_NOT_PENDING';end if;end $$;
create or replace function public.process_affiliate_payout(p_actor_id uuid,p_request_id uuid,p_decision text,p_reason text default null) returns void language plpgsql security definer set search_path='' as $$
declare v public.affiliate_payout_requests%rowtype;begin if not exists(select 1 from public.profiles where id=p_actor_id and role='admin') then raise exception 'ADMIN_REQUIRED';end if;select * into v from public.affiliate_payout_requests where id=p_request_id for update;if v.id is null or v.status<>'REQUESTED' then raise exception 'PAYOUT_NOT_REQUESTED';end if;
 if p_decision='PAID' then update public.affiliate_payout_requests set status='PAID',processed_at=now(),processed_by=p_actor_id where id=v.id;insert into public.affiliate_wallet_entries(affiliate_user_id,payout_request_id,entry_type,paid_delta,idempotency_key) values(v.affiliate_user_id,v.id,'PAYOUT_PAID',v.amount,'payout:'||v.id||':paid');
 elsif p_decision='REJECTED' then update public.affiliate_payout_requests set status='REJECTED',processed_at=now(),processed_by=p_actor_id,rejection_reason=nullif(trim(p_reason),'') where id=v.id;insert into public.affiliate_wallet_entries(affiliate_user_id,payout_request_id,entry_type,available_delta,idempotency_key) values(v.affiliate_user_id,v.id,'PAYOUT_RESTORED',v.amount,'payout:'||v.id||':restored');else raise exception 'INVALID_DECISION';end if;end $$;
revoke all on function public.request_affiliate_payout(uuid,numeric,text,text),public.release_affiliate_commission(uuid,uuid),public.process_affiliate_payout(uuid,uuid,text,text) from public,anon,authenticated;
grant execute on function public.request_affiliate_payout(uuid,numeric,text,text),public.release_affiliate_commission(uuid,uuid),public.process_affiliate_payout(uuid,uuid,text,text) to service_role;
